import { createSlice } from '@reduxjs/toolkit';

const initialState = {
    saved: {
        Id: void(0),
        NickName: void(0),
        Status: void(0)
    }
};

export const counterSlice = createSlice({
    name: 'counter',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        insert: (state) => {
            console.log('insert',state)
        },
        remove: (state) => {
            console.log('remove',state)
        },
        edit: (state) => {
            console.log('edit',state)
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
});

export const { insert, remove, edit } = counterSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const SelectUser = (state) => state.user;

export default counterSlice.reducer;
